### ISSUE TITLE
DOC: MAKE GSSOC BANNER DYNAMIC 💡

### ISSUE THREAD

**Issue by 0xabdulkhalid** [avinashkranjan/Friday#325] opened 2023-07-08 05:54 UTC
### What's wrong with the existing documentation

- The GSSOC Banner of this repository is in black so that the logo is not properly visible in Github Dark mode, actually over 85% users using Github in dark mode only.
- We want to resolve this issue as soon as possible.

### Add ScreenShots

| CURRENT STATE IN DARK THEME | DESIRED STATE IN DARK THEME |
|  :-----:   | :-----:  |
| ![](https://github.com/avinashkranjan/Friday/assets/92252895/9ab9eaa3-c844-4d4f-be53-6f7b0e561e39)| ![](https://user-images.githubusercontent.com/63473496/213306279-338f7ce9-9a9f-4427-8c2a-3e344874498f.png#gh-dark-mode-only) 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment] 2023-07-08 05:55
Hey there @avinashkranjan  👋🏻

Please make sure to assign this issue to me asap to make the work done!

Thank you.

**Comment by avinashkranjan** [comment] 2023-07-10 15:15
Go Ahead

**Comment by 0xabdulkhalid** [comment] 2023-07-15 05:11
@avinashkranjan a person has created a PR for this issue which i was assigned by you without your permisson.

Kindly close his PR and merge my PR to fix this issue.

Thank you for your attention!

**Comment by suman-somu** [comment] 2023-07-15 13:20
The issue is not fixed by your PR. The light mode is not working. 
Also, the method you used to handle dynamic handling of images is old. I have used the new format syntax for that.

**Comment by 0xabdulkhalid** [comment] 2023-07-15 17:19
Bro, the light mode is finely working then how can i show the screenshot ?

First of all as a fellow contributor please make sure to follow ethics while contributing.

**How can you open a PR without informing the Project Admin or the one who created this ?**

Doing these types of stuffs is strictly against contributing guidelines.

Hope you understood, let the Project Admin @avinashkranjan  handle this problem.

**Comment by suman-somu** [comment] 2023-07-16 17:10
First, I don't know how are you saying it's working fine when it's clearly not. 
![image](https://github.com/avinashkranjan/Friday/assets/75962762/627ae62e-947a-4aa4-a7fd-75f22ef64a1e)

Secondly, it was my mistake that I overlooked your commitment and started to work on it. I realised it after making the PR. 
After which, I didn't even mentioned once to merge my PR after that.

**Comment by 0xabdulkhalid** [comment] 2023-07-17 01:23
How can you see the image if the page still not properly loaded yet 🤦‍♂️

![image](https://github.com/avinashkranjan/Friday/assets/92252895/074ce407-5bb8-4a7a-8d6e-9966dfe1dca7)

Here's how it looks, just view it from view file from this PR.

![image](https://github.com/avinashkranjan/Friday/assets/92252895/0135e225-a811-4b6f-bfcb-c51f190c0abc)

I have already told you that **you are not permitted to open a PR for which not assigned to you yet**, You doesn't follow contributing guidelines here.

Please close that, that's all i can say.

Otherwise it will be closed by Project Admin.

**Comment by suman-somu** [comment] 2023-07-17 14:23
You are using old syntax for image insertion, which is why it's just never loads or takes much time.
  https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
The mistake is not with my network but with your code itself. And not just arguing over guidelines maybe you should have fixed it when I mentioned it earlier. 
Also, maintainers know the guidelines you are trying to specify in every message. The guidelines are meant to be for the betterment of the project and the PA will do same.

**Closed** 2023-07-18 05:24 UTC
Labels: documentation, level1, gssoc23
